In [98]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import classification_report
import load_MNIST

利用写好的load_MNIST模块中的load_data方法导入MNIST数据集
- Parameter
    - file_name:list 
        四个文件路径
        - list[0]: 训练集的图片数据文件路径
        - list[1]: 测试集的图片数据文件路径
        - list[2]: 训练集的标签文件路径
        - list[3]: 测试集的标签文件路径
- Return
    - train_data: numpy array
    - train_labels: list
    - test_data: numpy array
    - test_labels: list

In [105]:
file = ["C:/Users/wtser/Desktop/learnData/data/Mnist/train-images.idx3-ubyte",
       "C:/Users/wtser/Desktop/learnData/data/Mnist/t10k-images.idx3-ubyte",
       "C:/Users/wtser/Desktop/learnData/data/Mnist/train-labels.idx1-ubyte",
       "C:/Users/wtser/Desktop/learnData/data/Mnist/t10k-labels.idx1-ubyte"]  

train_data,train_labels,test_data,test_labels = load_MNIST.load_data(file)

#把训练集的标签进行改变，比如x被分为第二类，y = 1，但为了后续
train_y = LabelBinarizer().fit_transform(train_labels)

#为测试集和训练集的数据增加一维当作偏置值
train_data = np.c_[train_data,np.ones([train_data.shape[0],1])]
test_data = np.c_[test_data,np.ones([test_data.shape[0],1])]


In [103]:
print(train_data.shape,np.ones([train_data.shape[0],1]).shape)
print(np.c_[train_data,np.ones([train_data.shape[0],1])])

(60000, 785) (60000, 1)
[[0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]]


In [ ]:
print(train_data.shape)

In [107]:
class logisticRegression_softMax:
    def __init__(self,size):
        """
        初始化模型
        
        Parameters:
        ___________
        size: list of shape
            权重的规模
        """
        
        self.W = np.random.rand(size[0],size[1])
        
    def softMax(self,x):
        max_dict = [ [np.max(i)] for i in x]
        print(max_dict)
        print((x-max_dict))
        x = np.exp((x-max_dict))
        print(x)
        return np.array([ i/np.sum(i) for i in x])
    
    def softMax_deriv(self,x,y):
        return x - y
    
    def fit(self,X,Y,batch_size,epoch,alpha,count=10):
        """
        训练模型
        
        Parameters:
        ___________
        X:numpy array of shape
        Y:list of label
        batch_size: 批量梯度下降法的批量大小
        epoch:训练次数
        alpha:学习率
        """
        
        for i in range(epoch):
            batch_index = np.random.choice(X.shape[0],batch_size,True)
            batch_x = X[batch_index,:]
            batch_y = Y[batch_index]
            
            self.train(batch_x,batch_y,alpha)
            if i == 0 or (i+1)%count ==0:
                print("i-loss",self.calculate_loss(X,Y))
    
    def train(self,x,y,alpha):
        net = x.dot(self.W)
        print(net)
        out = self.softMax(net)
        print(out)
        deriv = self.softMax_deriv(out,y)

        self.W -= 1.0/x.shape[0] * alpha * x.T.dot(deriv)
    
    def predict(self,x):
        net = x.dot(self.W)
        out = self.softMax(net)
        return out
    
    def calculate_loss(self,x,y):
        predictions = self.predict(x)
        print(predictions[0])
        loss = -sum(np.sum(y*np.log(predictions),1))
        return loss

In [108]:
model = logisticRegression_softMax([train_data.shape[1],10])
# print(model.W)
# model.fit(train_data[:1000],train_y[:1000],batch_size=10,epoch=1,alpha=0.01,count=10)

In [111]:
print(model.softMax(np.array([[13861.56825424,14273.9267793,15230.02376196,14989.60642211
  ,15221.3726415,14213.86068133,15170.76363433,14587.1522964,
  14267.30468454,14812.21031282]])))


[[15230.02376196]]
[[-1368.45550772  -956.09698266     0.          -240.41733985
     -8.65112046 -1016.16308063   -59.26012763  -642.87146556
   -962.71907742  -417.81344914]]
[[0.00000000e+000 0.00000000e+000 1.00000000e+000 3.87325374e-105
  1.74930735e-004 0.00000000e+000 1.83507396e-026 6.37484947e-280
  0.00000000e+000 3.51499388e-182]]
[[0.00000000e+000 0.00000000e+000 9.99825100e-001 3.87257631e-105
  1.74900140e-004 0.00000000e+000 1.83475301e-026 6.37373451e-280
  0.00000000e+000 3.51437911e-182]]
